### ISSUE TITLE
Conversion glyphs2ufo

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Libre-Franklin#3]
Hi @djrrb !

Would you be able to assist with conversion of the Libre-Franklin from glyphs2ufo?

for the 'Single fonts folder' and the 'for GX fonts' if possible.

A couple issues to resolve before export:

• The master and instance values and names in the font info in the Glyph sources.

• There is an error with one of the accents. I think a possible reference to a composite that is in a background layer? Something related to one of these three glyphs?
/Abreveacute
/brevecomb.case
/brevecomb_acutecomb.case

Thanks!

**Comment by djrrb** [comment]
Yeah, there are no case-sensitive diacritics anymore, and these references exist in the background. Unfortunately, after I remove them, there is a `fontTools.ufoLib.errors.GlifLibError: offcurve occurs before line point.` which points to more malformatted data (or perhaps data from an earlier version of glyphs).

Using File > Export UFO in Glyphs works handles it though, even when glyphs2ufo doesn’t. So I just used that for my latest commit, and we can discuss whether it is sufficient to proceed.

**Comment by pichotta** [comment]
@djrrb 
<img width="1103" alt="unknown format" src="https://user-images.githubusercontent.com/6576107/88336471-0b83bb80-cd03-11ea-87f1-201a81f87fe8.png">

**Comment by djrrb** [comment]
try again 😉
