### ISSUE TITLE
Vertical metrics 

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/Libre-Franklin#4]
Funny that fontbakery catches this in the Italic VF but not the upright. Want to confirm what’s going on before making changes.

* 🔥 **FAIL** Libre Franklin Thin Italic: OS/2 sTypoAscender is 847 when it should be 966 [code: bad-typo-ascender]
* 🔥 **FAIL** Libre Franklin Thin Italic: OS/2 sTypoDescender is -165 when it should be -246 [code: bad-typo-descender]
* 🔥 **FAIL** Libre Franklin Thin Italic: hhea Ascender is 847 when it should be 966 [code: bad-hhea-ascender]
* 🔥 **FAIL** Libre Franklin Thin Italic: hhea Descender is -165 when it should be -246 [code: bad-hhea-descender]

</details>

**Comment by m4rc1e** [comment]
hmm, I'm just diffing this family and it's still not right.

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/93894604-cff77480-fce6-11ea-8777-5c183113efca.gif)

I expect the vertical metrics to visually match the previous release.

**Comment by pichotta** [comment]
@moyogo   Do you have insight into the Libre Franklin vertical metrics differences?

**Comment by moyogo** [comment]
I just noticed the use_typo_metrics flags is missing even though I mention it in a commit.
I’ll enable it and see if diffbrowsers shows any difference.
